# Generated by Django 4.2.1 on 2024-06-15 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_alter_teach_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcanceled',
            name='teacher_to_replace',
            field=models.ForeignKey(blank=True, db_column='teacher_to_replace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporaryclass',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
