# Generated by Django 4.2.1 on 2024-07-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_classcanceled_teacher_to_replace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_leader_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
