# Generated by Django 4.2.1 on 2024-07-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
