# Generated by Django 4.2.1 on 2024-06-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_user_alter_studentalert_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
